name: Scan Pull Request with Frogbot

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
      - dev
      - lib
      - backend-end
      - front-end


env:
  WORKING_DIRECTORY: master-ugr.calculator.back-end/calculator.backend
  WORKING_DIRECTORY_FRONTEND: master-ugr.calculator.front-end/calculator.frontend
jobs:
  scan-pull-request-backend:
    runs-on: ubuntu-latest
    environment: frogbot

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scan pull request with Frogbot
        uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_WORKING_DIR: "${{ env.WORKING_DIRECTORY }}"

  scan-pull-request-front:
    runs-on: ubuntu-latest
    environment: frogbot

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scan pull request with Frogbot
        uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_WORKING_DIR: "${{ env.WORKING_DIRECTORY_FRONTEND }}"